version: '3.9'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: car_dealer
      MYSQL_USER: car_dealer
      MYSQL_PASSWORD: passwd
    networks:
      - database-network
networks:
  database-network:
    driver: bridge
